L2RPCHost = "http://l2:8545"
BitcoinRPCHost = "bitcoindsim:18443"
BitcoinRPCUser = "rpcuser"
BitcoinRPCPass = "rpcpass"
BitcoinDisableTLS = true
DBFilePath = "/home/finality-gadget/data.db"
FGContractAddress = "bbn1ghd753shjuwexxywmgs4xz7x2q732vcnkm6h2pyv9s6ah3hylvrqxxvh0f"
BBNChainID = "chain-test"
BBNRPCAddress = "http://babylondnode0:26657"
GRPCListener = "0.0.0.0:50051"
PollInterval = "10s"