L2RPCHost = "http://l2:8545"
BitcoinRPCHost = "bitcoindsim:18443"
DBFilePath = "/home/finality-gadget/data.db"
FGContractAddress = "bbn1ghd753shjuwexxywmgs4xz7x2q732vcnkm6h2pyv9s6ah3hylvrqxxvh0f"
BBNChainID = "chain-test"
BBNRPCAddress = "http://babylondnode0:26657"
GRPCServerPort = "50051"
PollInterval = "10s"